### ISSUE TITLE
Dos

### ISSUE THREAD

**Issue by LocoabordoR8** [BlindZoneLLC/qute-apk#1]
> https://github.com/BlindZoneLLC/qute-apk/issues 

 _Originally posted by @LocoabordoR8 in [bb63f6a](https://github.com/BlindZoneLLC/qute-apk/commit/bb63f6a53cba9b35c3413d79013b90a7ed098b8e#r150543358)_

**Comment by BlindZoneLLC** [comment]
> > https://github.com/BlindZoneLLC/qute-apk/issues 
> 
>  _Originally posted by @LocoabordoR8 in [bb63f6a](https://github.com/BlindZoneLLC/qute-apk/commit/bb63f6a53cba9b35c3413d79013b90a7ed098b8e#r150543358)_

Hello. How we can help?

**Comment by LocoabordoR8** [comment]
git clone https://github.com/git/git
